# Generated by Django 6.0.5 on 2026-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
