# Generated by Django 6.0.5 on 2026-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_delivery_type_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Use Cloudinary or S3 for production on Vercel', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Use Cloudinary or S3 for production on Vercel', null=True, upload_to='products/'),
        ),
    ]
